// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSW54MBWf_r0fxz_F8VLDLMAlxy0cM_Vk',
    appId: '1:576159579227:android:8ce317e0ba80738736d37e',
    messagingSenderId: '576159579227',
    projectId: 'note-taker-d5794',
    storageBucket: 'note-taker-d5794.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHgobSPgYHtSDSQcVd8pc9vPshNqwqkdc',
    appId: '1:576159579227:ios:e5b7b8eabfabff3936d37e',
    messagingSenderId: '576159579227',
    projectId: 'note-taker-d5794',
    storageBucket: 'note-taker-d5794.firebasestorage.app',
    androidClientId: '576159579227-mvn4ki6f3vnse7gsdsv32q1hsb8o31o6.apps.googleusercontent.com',
    iosClientId: '576159579227-dvm2t4sdarh2as97a2jingvghdbfvr69.apps.googleusercontent.com',
    iosBundleId: 'com.example.notetaker',
  );

}